name: Tests
on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.rst'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.13', python: '3.13', tox: 'py313,py-no-babel'}
          - {name: '3.12', python: '3.12', tox: py312}
          - {name: '3.11', python: '3.11', tox: py311}
          - {name: '3.10', python: '3.10', tox: py310}
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: 'PyPy310', python: 'pypy-3.10', tox: pypy310}
          - {name: 'PyPy39', python: 'pypy-3.9', tox: pypy39}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements/*.txt'
      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install tox
      - run: tox -e ${{ matrix.tox }}
